"""Build p3/sweep/SETTINGS.md from encode_log.json, results.csv and manifest.json.

Resolution / fps / pix_fmt are not in the log, so they are read from the stream headers of the
encodes already on disk (no re-encoding). "Varies" = knobs that differ from the encoder's reference arm.
"""
import collections
import json
import os

import av
import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
LOG = json.load(open(os.path.join(HERE, "encode_log.json")))["logs"]
MAN = json.load(open(os.path.join(HERE, "manifest.json")))
R = pd.read_csv(os.path.join(HERE, "results.csv"))
BASE = {"libx264": "x264_crf23", "h264_nvenc": "nvenc_qp28", "mpeg4": "mpeg4_q4"}
SEI_KEYS = ["crf", "qp", "ref", "bframes", "b_adapt", "b_pyramid", "threads", "sliced_threads", "me", "me_range",
            "keyint"]


def sei(s, k):
    for tok in (s or "").split():
        if tok.startswith(k + "="):
            return tok.split("=", 1)[1]
    return None


def rng(vals, nd=1):
    v = [x for x in vals if x is not None and not (isinstance(x, float) and np.isnan(x))]
    if not v:
        return "–"
    lo, hi = min(v), max(v)
    return f"{lo:.{nd}f}" if round(lo, nd) == round(hi, nd) else f"{lo:.{nd}f}–{hi:.{nd}f}"


def uniq(vals):
    u = sorted({"–" if v is None else str(v) for v in vals})
    return ", ".join(u)


def main():
    ok = [lg for lg in LOG if lg["status"] == "ok"]
    arms = list(dict.fromkeys(lg["encode_id"] for lg in LOG))
    by = collections.defaultdict(list)
    for lg in ok:
        by[lg["encode_id"]].append(lg)
    knobs = {a: by[a][0]["knobs"] for a in arms}

    # stream headers of every encode on disk
    hdr = collections.Counter()
    for lg in ok:
        p = os.path.join(HERE, "encodes", lg["pass"], f"{lg['encode_id']}__{lg['sequence']}.mp4")
        with av.open(p) as c:
            st = c.streams.video[0]
            hdr[(st.codec_context.width, st.codec_context.height, st.codec_context.pix_fmt,
                 str(st.average_rate))] += 1
    keyints = collections.Counter(k.get("keyint") for k in knobs.values())
    x = [lg for lg in ok if lg["codec"] == "libx264"]

    L = ["# Paper 3 — Sintel sweep: encoder settings", "",
         "Generated by `make_settings.py` from `encode_log.json`, `results.csv` and `manifest.json` "
         "(stream geometry read from the encode headers). Do not edit by hand.", "",
         "## Software", "",
         f"- Python {MAN['python']}, PyAV {MAN['pyav']}, numpy {MAN['numpy']}, pandas {MAN['pandas']}",
         "- FFmpeg libraries: " + ", ".join(f"{k} {v}" for k, v in MAN["ffmpeg_libs"].items()),
         f"- x264 build: {MAN['x264_build']}",
         f"- NVIDIA: {MAN['nvidia']}",
         f"- Pre-registration commit `{MAN['prereg_commit']}`; code frozen at `{MAN['code_frozen_commit']}`; "
         f"run at `{MAN['git_hash']}`; code sha256 `{MAN['code_sha256']}`",
         f"- Run {MAN['start_time']} → {MAN['end_time']} ({MAN['runtime_s']:.0f} s); {MAN['n_runs']} runs, "
         f"{MAN['n_failures']} failures, {MAN['n_mismatches']} check mismatches", "",
         "## Shared by every arm", "",
         "- Stream headers over all encodes (width × height, pix_fmt, fps: count): "
         + "; ".join(f"{w}×{h}, {pf}, {fps}: {n}" for (w, h, pf, fps), n in hdr.items()),
         f"- Source: MPI-Sintel training, {len(MAN['sequences'])} sequences, 1024×436 frames "
         "(H.264 codes 448 rows, padded)",
         "- keyint (knob value: arms): " + "; ".join(f"{k}: {n}" for k, n in keyints.items()),
         f"- x264 SEI scenecut: {uniq(sei(lg['x264_sei'], 'scenecut') for lg in x)} "
         f"(keyint_min in SEI: {uniq(sei(lg['x264_sei'], 'keyint_min') for lg in x)}; x264 clamps min-keyint to keyint/2+1)",
         "- NVENC and mpeg4 have no scene-cut option set; I-frame placement is checked through frame types: "
         f"I-frames per encode = {uniq(lg['n_I'] for lg in ok if lg['codec'] != 'libx264' and lg['knobs'].get('keyint') == 250)} "
         "for keyint 250 arms",
         "- Encodes with more I-frames than keyint implies (scene-change I-frames; mpeg4 and NVENC scene-cut "
         "detection was not disabled): "
         + ("; ".join(f"{lg['pass']} {lg['encode_id']} {lg['sequence']} ({lg['n_I']} I: {lg['types']})"
                      for lg in ok if lg["n_I"] != -(-len(lg["types"]) // lg["knobs"]["keyint"])) or "none"),
         "", "## Arms", "",
         "Decoded QP = mean per-MB QP of that frame type, min–max over sequences (PyAV `qp_map`; mpeg4 values "
         "are FFmpeg's internal 2·q). Slices = bitstream slices (H.264) or video packets (mpeg4) per frame, "
         "min–max over all frames and sequences. SEI fields apply to x264 only.", ""]
    cols = ["arm", "encoder", "varies (vs " + ", ".join(BASE.values()) + ")", "avcodec options"] + \
           [f"SEI {k}" for k in SEI_KEYS] + ["I QP", "P QP", "B QP", "slices/frame", "kbps (final)",
                                              "kbps (clean)", "passes", "runs ok"]
    L += ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for a in arms:
        g = by[a]
        codec = g[0]["codec"]
        kb, bk = knobs[a], knobs[BASE[codec]]
        var = [f"{k}={kb.get(k)}" for k in sorted(set(kb) | set(bk)) if kb.get(k) != bk.get(k)]
        opts = uniq(json.dumps(lg["options"], sort_keys=True) for lg in g)
        row = [a, codec, ", ".join(var) or "(reference)", f"`{opts}`"]
        for k in SEI_KEYS:
            row.append(uniq(sei(lg["x264_sei"], k) for lg in g) if codec == "libx264" else "–")
        row += [rng([lg["mean_i_qp"] for lg in g]), rng([lg["mean_p_qp"] for lg in g]),
                rng([lg["mean_b_qp"] for lg in g]),
                rng([lg["slices_min"] for lg in g] + [lg["slices_max"] for lg in g], 0)]
        for p in ("final", "clean"):
            row.append(rng([lg["bitrate_kbps"] for lg in g if lg["pass"] == p], 0))
        passes = sorted({lg["pass"] for lg in g})
        nrun = {p: sum(lg["pass"] == p for lg in g) for p in passes}
        row += [", ".join(passes), ", ".join(f"{p} {n}/23" for p, n in nrun.items())]
        L.append("| " + " | ".join(str(c).replace("|", "\\|") for c in row) + " |")
    n_arms = len(arms)
    rows_arms = R["encode_id"].nunique()
    L += ["", f"{n_arms} arms in encode_log.json; {rows_arms} arms in results.csv.", ""]
    open(os.path.join(HERE, "SETTINGS.md"), "w", encoding="utf-8").write("\n".join(L))
    print("wrote SETTINGS.md,", n_arms, "arms")


if __name__ == "__main__":
    main()
