"""Review-3 item R1: the two "8.7%" values and the "22/23" count.

(a) Sintel stale/valid, FINAL pass, tau = 1, from p3/sweep/results.csv: median over the 23 sequences of
    nvenc_qp28 (group d1; NVENC QP 28 bf 0) and nvenc_qp28_bf2 (group B_naive; NVENC QP 28 bf 2, DEFAULT B QP).
    Counts of sequences where B minus baseline > 0.01 and > 0 (and > 0.001, the pre-registered P2 margin).
    The same counts for the pre-registered B=P arm (nvenc_qp28_bf2_bqeq, B_naive) are given beside it.
(b) Sintel STALE_MOV medians of the NVENC "B=P" pair from p3/review_fixes/sintel_stale_mov.csv.
Writes r1_eight_point_seven.md / .csv. Exploratory reporting; no verdict changes.
"""
import os

import pandas as pd

from _common import P3, HERE, S, f, pct, table, write

BASE = ("nvenc_qp28", "d1")
BARMS = (("NVENC QP 28 bf 2, default B QP", "nvenc_qp28_bf2", "B_naive"),
         ("NVENC QP 28 bf 2, B=P (pre-registered P2 arm)", "nvenc_qp28_bf2_bqeq", "B_naive"))


def main():
    b0 = S(*BASE)
    rows, lines = [], []
    rows.append({"source": "p3/sweep/results.csv (final, tau=1)", "metric": "stale_of_valid",
                 "arm": "NVENC QP 28 bf 0", "encode_id": BASE[0], "group": BASE[1], "n": int(b0.notna().sum()),
                 "median": b0.median()})
    for lab, eid, grp in BARMS:
        b = S(eid, grp)
        d = b - b0
        rows.append({"source": "p3/sweep/results.csv (final, tau=1)", "metric": "stale_of_valid", "arm": lab,
                     "encode_id": eid, "group": grp, "n": int(b.notna().sum()), "median": b.median(),
                     "n_diff_gt_0.01": int((d > 0.01).sum()), "n_diff_gt_0.001": int((d > 0.001).sum()),
                     "n_diff_gt_0": int((d > 0).sum()), "median_diff": d.median()})
    sm = pd.read_csv(os.path.join(P3, "review_fixes", "sintel_stale_mov.csv"))
    smp = {}
    for eid, grp, lab in (("nvenc_qp28", "d1", "NVENC QP 28 bf 0"),
                          ("nvenc_qp28_bf2_bqeq", "B_naive", "NVENC QP 28 bf 2, B=P (pre-registered P2 arm)")):
        s = sm[(sm.encode_id == eid) & (sm.group == grp)]
        # nvenc_qp28 d1 appears twice per sequence (labels "NVENC QP 28" and "NVENC QP 28 bf 0"); same values
        assert (s.groupby("sequence")["stale_mov"].nunique() == 1).all()
        s = s.drop_duplicates("sequence").set_index("sequence")["stale_mov"]
        smp[eid] = s
        rows.append({"source": "p3/review_fixes/sintel_stale_mov.csv", "metric": "STALE_MOV", "arm": lab,
                     "encode_id": eid, "group": grp, "n": int(s.notna().sum()), "median": s.median()})
    d = smp["nvenc_qp28_bf2_bqeq"] - smp["nvenc_qp28"]
    rows[-1].update({"n_diff_gt_0.01": int((d > 0.01).sum()), "n_diff_gt_0.001": int((d > 0.001).sum()),
                     "n_diff_gt_0": int((d > 0).sum()), "median_diff": d.median()})
    df = pd.DataFrame(rows)
    df.to_csv(os.path.join(HERE, "r1_eight_point_seven.csv"), index=False)

    cnt = lambda r, k: "–" if pd.isna(r.get(k)) else f"{int(r[k])}/{int(r['n'])}"  # noqa: E731
    for r in rows:
        lines.append([r["metric"], r["arm"], f"`{r['encode_id']}` / `{r['group']}`", f(r["median"]),
                      pct(r["median"], 1), cnt(r, "n_diff_gt_0.01"), cnt(r, "n_diff_gt_0.001"),
                      cnt(r, "n_diff_gt_0"), f(r.get("median_diff", float("nan")))])
    sov_def = rows[1]["median"]
    smv_bqeq = rows[4]["median"]
    L = ["# R1: the two \"8.7%\" values and the \"22/23\" count", "",
         "Exploratory reporting, no verdict changes. Generated by `r1_eight_point_seven.py`. Sintel, 23 sequences, "
         "FINAL pass, tau = 1 px. \"B minus baseline\" is per sequence, against NVENC QP 28 bf 0 (`nvenc_qp28`, d1) "
         "in the same metric.", "",
         table(["metric", "arm", "encode / group", "median", "median (%)", "B - bf 0 > 0.01", "B - bf 0 > 0.001",
                "B - bf 0 > 0", "median per-seq diff"], lines), "",
         "## Reading", "",
         f"- stale/valid, NVENC QP 28 bf 2 with the **default** B QP (`nvenc_qp28_bf2`): median {f(sov_def)} "
         f"({pct(sov_def, 1)}). STALE_MOV, NVENC QP 28 bf 2 **B=P** (`nvenc_qp28_bf2_bqeq`): median {f(smv_bqeq)} "
         f"({pct(smv_bqeq, 1)}). They print the same to one decimal, but they are different "
         f"numbers: different arm (default B QP vs B = P), different metric (stale/valid vs stale/moving) and "
         f"different value at 4 decimals ({f(sov_def)} vs {f(smv_bqeq)}).",
         f"- The pre-registered B=P arm in stale/valid has median {f(rows[2]['median'])} "
         f"({pct(rows[2]['median'], 1)}), not 8.7%. \"3.3 -> 8.7%\" in stale/valid is the default-B-QP arm; "
         f"its baseline is {f(rows[0]['median'])}. In STALE_MOV the B=P pair is {f(rows[3]['median'])} -> "
         f"{f(smv_bqeq)}, i.e. its baseline is not 3.3%.",
         "- \"22/23\" counts (B - bf 0): see the three count columns. The pre-registered P2 count (B=P arm, "
         f"stale/valid, > 0.001) is {cnt(rows[2], 'n_diff_gt_0.001')}; the default-B-QP arm gives "
         f"{cnt(rows[1], 'n_diff_gt_0.01')} (> 0.01), {cnt(rows[1], 'n_diff_gt_0.001')} (> 0.001) and "
         f"{cnt(rows[1], 'n_diff_gt_0')} (> 0)."]
    write("r1_eight_point_seven.md", L)


if __name__ == "__main__":
    main()
