"""Review-3 item R2: the MPEG-4 P1 row, in the same format as the x264 and NVENC P1 rows.

Reads p3/PREREGISTRATION.md (the rule text, quoted verbatim) and p3/sweep/independent_verdicts.txt (the recorded
rows), and recounts all three P1 rows from p3/sweep/results.csv (final, tau = 1, group d1) to check them.
Writes r2_mpeg4_p1.md / .csv. No verdict changes.
"""
import os
import re

import pandas as pd

from _common import P3, HERE, S, f, table, write

P1ROWS = (("x264 CRF 45 vs 12", "x264_crf45", "x264_crf12", 18, "P1 x264 CRF45-CRF12", True),
          ("NVENC QP 45 vs 18", "nvenc_qp45", "nvenc_qp18", 18, "P1 NVENC QP45-QP18", True),
          ("MPEG-4 q 31 vs 2", "mpeg4_q31", "mpeg4_q2", 16, "P1 mpeg4 q31-q2 (not kill)", False))
MARGIN = 0.001


def main():
    pre = open(os.path.join(P3, "PREREGISTRATION.md"), encoding="utf-8").read().splitlines()
    i = next(k for k, ln in enumerate(pre) if ln.startswith("P1 Quantiser"))
    p1_text = pre[i:i + 3]
    kill = [ln for ln in pre if ln.startswith("- P1 fails")]
    iv = open(os.path.join(P3, "sweep", "independent_verdicts.txt"), encoding="utf-8").read().splitlines()

    rows, lines = [], []
    for lab, hi, lo, need, ivkey, is_kill in P1ROWS:
        d = S(hi, "d1") - S(lo, "d1")
        n, N = int((d > MARGIN).sum()), int(d.notna().sum())
        rec = [ln for ln in iv if ln.startswith(ivkey) and re.search(r"\d+/\d+\s+>=", ln)]
        rec_count = re.search(r"(\d+/\d+)", rec[0]).group(1) if rec else None
        rec_verdict = rec[0].split()[-1] if rec else None
        verdict = "PASS" if n >= need else "FAIL"
        not_passing = ", ".join(f"{s} ({d[s]:+.4f})" for s in d.index if not d[s] > MARGIN) or "none"
        rows.append({"prediction": f"P1 {lab}", "rule": f"stale/valid({hi}) - stale/valid({lo}) > {MARGIN}",
                     "threshold": f">= {need}/23", "count": f"{n}/{N}", "verdict": verdict,
                     "kill_rule_row": is_kill, "recorded_count": rec_count, "recorded_verdict": rec_verdict,
                     "recount_matches_record": rec_count == f"{n}/{N}" and rec_verdict == verdict,
                     "median_diff": d.median(), "sequences_not_passing": not_passing})
        lines.append([f"P1 {lab}", f"stale/valid({hi}) - stale/valid({lo}) > {MARGIN}, per sequence",
                      f">= {need}/23", f"{n}/{N}", verdict, "yes" if is_kill else "**no (reported only)**",
                      f"{rec_count} {rec_verdict}", f(d.median()), not_passing])
    pd.DataFrame(rows).to_csv(os.path.join(HERE, "r2_mpeg4_p1.csv"), index=False)
    m = rows[2]
    L = ["# R2: the MPEG-4 P1 row", "",
         "Generated by `r2_mpeg4_p1.py`. Sintel, FINAL pass, tau = 1 px, group d1 (P-frame vectors, d = 1), "
         "stale/valid, 23 sequences.", "",
         "## Pre-registered text (p3/PREREGISTRATION.md, verbatim)", "", "```", *p1_text, "```", "",
         "Kill rule for P1 (verbatim):", "", "```", *kill, "```", "",
         "## P1 rows", "",
         table(["prediction", "rule", "threshold", "count", "verdict", "part of the kill rule",
                "recorded in independent_verdicts.txt", "median per-seq diff", "sequences not passing"], lines), "",
         "## Plain statement", "",
         f"- MPEG-4 P1 **was** written into the pre-registration, with a threshold (>= 16/23), but explicitly as "
         f"\"reported ... not part of the kill rule\". It is a pre-registered prediction, not a verdict row that "
         f"can kill a claim. Its outcome: {m['count']} sequences with diff > {MARGIN}, threshold "
         f"{m['threshold']} -> {m['verdict']} (recount matches independent_verdicts.txt: {'yes' if m['recount_matches_record'] else 'NO'}).",
         "- The x264 and NVENC P1 rows are kill-rule rows (threshold >= 18/23). Recounts match the record: "
         + ", ".join(f"{r['prediction']} {'yes' if r['recount_matches_record'] else 'NO'}" for r in rows[:2]) + "."]
    write("r2_mpeg4_p1.md", L)


if __name__ == "__main__":
    main()
