"""Review-3 item R3: fold changes, Sintel stale/valid, FINAL pass, tau = 1 px, 23 sequences.

For each contrast: median low, median high, ratio of medians (high / low) and the median of the per-sequence
ratios high / low. A sequence whose low value is 0 has no finite ratio; it is left out of the per-sequence median
and counted in the table.
Contrasts: x264 CRF 12 -> 45; NVENC QP 18 -> 45; x264 QP 24 bf 0 -> B (pb1, B_naive); NVENC QP 28 bf 0 -> B=P
(bqeq, B_naive); and the three codecs at matched quality: per codec, the arm of its main bf 0 series whose median
PSNR-Y is closest to 41 dB (the encodes behind the draft's 0.34% / 3.3% / 16%), compared pairwise.
Writes r3_fold_changes.md / .csv. Exploratory reporting; no verdict changes.
"""
import os

import numpy as np
import pandas as pd

from _common import HERE, S, SCONTRASTS, matched_arms, f, pct, table, write


def fold(lab, lo, glo, hi, ghi, tau=1.0):
    a, b = S(lo, glo, tau=tau), S(hi, ghi, tau=tau)
    ok = a > 0
    r = (b[ok] / a[ok])
    return {"contrast": lab, "tau": tau, "low": f"{lo} ({glo})", "high": f"{hi} ({ghi})", "n": int(a.notna().sum()),
            "median_low": a.median(), "median_high": b.median(), "ratio_of_medians": b.median() / a.median(),
            "median_per_seq_ratio": r.median(), "n_low_zero": int((~ok).sum()),
            "min_per_seq_ratio": r.min(), "max_per_seq_ratio": r.max(),
            "n_ratio_gt_1": int((r > 1).sum())}


def contrasts():
    m = matched_arms()
    out = [(lab, lo, glo, hi, ghi) for lab, lo, glo, hi, ghi in SCONTRASTS]
    for c1, c2 in (("x264", "NVENC"), ("x264", "MPEG-4"), ("NVENC", "MPEG-4")):
        out.append((f"matched ~41 dB: {c1} {m[c1][0]} -> {c2} {m[c2][0]}", m[c1][0], "d1", m[c2][0], "d1"))
    return out, m


def main():
    cs, m = contrasts()
    rows = [fold(*c) for c in cs]
    pd.DataFrame(rows).to_csv(os.path.join(HERE, "r3_fold_changes.csv"), index=False)
    lines = [[r["contrast"], f(r["median_low"]), f(r["median_high"]), f"{r['ratio_of_medians']:.2f}x",
              f"{r['median_per_seq_ratio']:.2f}x", f"{r['min_per_seq_ratio']:.2f}x – {r['max_per_seq_ratio']:.2f}x",
              f"{r['n_ratio_gt_1']}/{r['n'] - r['n_low_zero']}", r["n_low_zero"]] for r in rows]
    mlines = [[c, f"`{eid}`", f"{ps:.2f}", f(S(eid, 'd1').median()), pct(S(eid, 'd1').median())]
              for c, (eid, ps) in m.items()]
    L = ["# R3: fold changes (Sintel, stale/valid, FINAL pass, tau = 1 px)", "",
         "Exploratory reporting, no verdict changes. Generated by `r3_fold_changes.py`. 23 sequences. "
         "\"ratio of medians\" = median(high) / median(low); \"median per-seq ratio\" = median over sequences of "
         "high / low in the same sequence (sequences with low = 0 are left out and counted).", "",
         table(["contrast", "median low", "median high", "ratio of medians", "median per-seq ratio",
                "per-seq ratio range", "sequences with ratio > 1", "sequences with low = 0"], lines), "",
         "## Matched-quality encodes (closest median PSNR-Y to 41 dB in each codec's main bf 0 series)", "",
         table(["codec", "encode", "median PSNR-Y (dB)", "median stale/valid", "as %"], mlines)]
    write("r3_fold_changes.md", L)


if __name__ == "__main__":
    main()
