"""Review-3 item R5: the R3 contrasts at tau = 0.5 and 2 px (tau = 1 shown for reference). SUPPLEMENTARY; the
pre-registered verdicts are at tau = 1 and are not changed.

Sintel (p3/sweep/results.csv, FINAL pass): stale/valid, 23 sequences, the R3 contrasts (r3_fold_changes.contrasts:
quality ends, matched-QP B pairs, and the three matched ~41 dB codec pairs).
CCTV confirmatory test (p3/virat_confirm/results.csv, which holds tau = 0.5, 1 and 2 for every clip/arm/group):
STALE_MOV over the 27 eligible clips, C1-C4. The CCTV test has no MPEG-4 arm and no x264 CRF 23 arm, so the
matched-quality codec contrasts are "not available" there. No flow is recomputed.
Per contrast and tau: median low, median high, median per-unit paired difference (high - low) and the number of
units with a rise > 0.01.
Writes r5_tau_appendix.md / .csv.
"""
import os

import pandas as pd

from _common import HERE, S, V, CPREDS, TAUS, eligible, f, table, write
from r3_fold_changes import contrasts

RULE = 0.01


def row(data, lab, a, b, tau, unit):
    d = b - a
    return {"data": data, "contrast": lab, "tau": tau, "n": int(d.notna().sum()), "median_low": a.median(),
            "median_high": b.median(), "median_diff": d.median(), "n_rise_gt_0.01": int((d > RULE).sum()),
            "available": True, "unit": unit}


def main():
    cs, _ = contrasts()
    clips = list(eligible().index)
    rows = []
    for lab, lo, glo, hi, ghi in cs:
        for tau in TAUS:
            rows.append(row("Sintel (stale/valid)", lab, S(lo, glo, tau=tau), S(hi, ghi, tau=tau), tau, "sequences"))
    for key, lo, glo, hi, ghi in CPREDS:
        for tau in TAUS:
            a, b = V(lo, glo, tau=tau).reindex(clips), V(hi, ghi, tau=tau).reindex(clips)
            if a.isna().any() or b.isna().any():
                rows.append({"data": "CCTV (STALE_MOV)", "contrast": key, "tau": tau, "available": False})
            else:
                rows.append(row("CCTV (STALE_MOV)", key, a, b, tau, "clips"))
    for lab, *_ in cs[4:]:
        for tau in TAUS:
            rows.append({"data": "CCTV (STALE_MOV)", "contrast": lab, "tau": tau, "available": False})
    df = pd.DataFrame(rows)
    df.to_csv(os.path.join(HERE, "r5_tau_appendix.csv"), index=False)

    def lines(d):
        out = []
        for r in d.to_dict("records"):
            if not r["available"]:
                out.append([r["contrast"], r["tau"]] + ["not available"] * 4)
            else:
                out.append([r["contrast"], r["tau"], f(r["median_low"]), f(r["median_high"]), f(r["median_diff"]),
                            f"{int(r['n_rise_gt_0.01'])}/{int(r['n'])}"])
        return out

    hdr = ["contrast", "tau (px)", "median low", "median high", "median paired diff", "rise > 0.01"]
    L = ["# R5: tau appendix (tau = 0.5 and 2 px; tau = 1 for reference)", "",
         "Supplementary; verdicts stay at tau = 1. Generated by `r5_tau_appendix.py` from saved results only "
         "(no flow recomputed). Sintel: FINAL pass, stale/valid, 23 sequences. CCTV: confirmatory test, STALE_MOV, "
         f"{len(clips)} eligible clips; tau = 0.5 and 2 are stored in p3/virat_confirm/results.csv. The CCTV test has "
         "no MPEG-4 or x264 CRF 23 arm, so the matched-quality contrasts are not available there. "
         "\"rise > 0.01\" counts sequences / clips with high - low > 0.01.", "",
         "## Sintel, stale/valid", "", table(hdr, lines(df[df.data.str.startswith("Sintel")])), "",
         "## CCTV confirmatory test, STALE_MOV", "", table(hdr, lines(df[df.data.str.startswith("CCTV")]))]
    write("r5_tau_appendix.md", L)


if __name__ == "__main__":
    main()
