"""Review follow-up B: Sintel STALE_MOV (stale cells / moving cells), the confirmatory CCTV test's metric, on the
saved Sintel sweep. EXPLORATORY REPORTING - no new verdicts; the 0.01 rule is borrowed from the CCTV
pre-registration (d62753f) and was not pre-registered for Sintel.

stale_cells: p3/sweep/results.csv, pass = final, tau = 1 (as collected; the rows used here are checked to be
identical in p3/sweep_rerun/results.csv).
moving cells: valid cells (gt_cover >= 0.5) with |GT| > 2 px, from the Sintel GT (lib.gt_grid, as the sweep's
load_seq), summed over the frames of the row's frame group. A row's frames are read from the sweep's own
blocks/final/<encode>__<seq>__frames.parquet (column group; B_naive rows use the frames with group B).
Self-check: the same per-frame GT gives valid cells summed over those frames, which must equal results.csv
valid_cells on every row used.
Outputs: p3/review_fixes/sintel_stale_mov.md, sintel_stale_mov.csv. No existing results file is modified.
"""
import os

import numpy as np
import pandas as pd

from _common import HERE, P3, MOVING_GT, gt_cells, sequences

TAU = 1.0
RULE = 0.01
CRFS = (12, 18, 23, 28, 33, 38, 45)
NQPS = (18, 23, 28, 33, 38, 45)
MQS = (2, 4, 8, 16, 31)
# (label, encode_id, results.csv group, frames-parquet group)
ROWS = ([(f"x264 CRF {c}", f"x264_crf{c}", "d1", "d1") for c in CRFS]
        + [(f"NVENC QP {q}", f"nvenc_qp{q}", "d1", "d1") for q in NQPS]
        + [(f"MPEG-4 q{q}", f"mpeg4_q{q}", "d1", "d1") for q in MQS]
        + [("x264 QP 24 bf 0", "x264_qp24", "d1", "d1"),
           ("x264 QP 24 bf 2 (B, naive)", "x264_qp24_bf2_pb1", "B_naive", "B"),
           ("NVENC QP 28 bf 0", "nvenc_qp28", "d1", "d1"),
           ("NVENC QP 28 bf 2 B=P (B, naive)", "nvenc_qp28_bf2_bqeq", "B_naive", "B")])
COMPS = (("x264 CRF 45 - CRF 12", "x264 CRF 45", "x264 CRF 12"),
         ("NVENC QP 45 - QP 18", "NVENC QP 45", "NVENC QP 18"),
         ("MPEG-4 q31 - q2", "MPEG-4 q31", "MPEG-4 q2"),
         ("x264 QP 24: B - bf 0", "x264 QP 24 bf 2 (B, naive)", "x264 QP 24 bf 0"),
         ("NVENC QP 28: B=P - bf 0", "NVENC QP 28 bf 2 B=P (B, naive)", "NVENC QP 28 bf 0"))
KEYCOLS = ["valid_cells", "stale_cells"]


def main():
    res = pd.read_csv(os.path.join(P3, "sweep", "results.csv"))
    res = res[(res["pass"] == "final") & (res.tau == TAU)].set_index(["encode_id", "sequence", "group"])
    rer = pd.read_csv(os.path.join(P3, "sweep_rerun", "results.csv"))
    rer = rer[(rer["pass"] == "final") & (rer.tau == TAU)].set_index(["encode_id", "sequence", "group"])
    seqs = sequences()
    out, mism = [], []
    for seq in seqs:
        gt, _ = gt_cells(seq)
        mov_t = {t: int((g["valid"] & (g["gmag"] > MOVING_GT)).sum()) for t, g in gt.items()}
        val_t = {t: int(g["valid"].sum()) for t, g in gt.items()}
        for lab, eid, grp, fgrp in ROWS:
            fr = pd.read_parquet(os.path.join(P3, "sweep", "blocks", "final", f"{eid}__{seq}__frames.parquet"),
                                 columns=["frame", "group"])
            ts = fr.loc[fr.group == fgrp, "frame"].tolist()
            moving, valid = sum(mov_t[t] for t in ts), sum(val_t[t] for t in ts)
            row = res.loc[(eid, seq, grp)]
            if int(row.valid_cells) != valid:
                mism.append(f"valid_cells {eid} {seq} {grp}: results {int(row.valid_cells)} vs GT recount {valid}")
            r2 = rer.loc[(eid, seq, grp)]
            if any(int(row[k]) != int(r2[k]) for k in KEYCOLS):
                mism.append(f"sweep vs sweep_rerun differ: {eid} {seq} {grp}")
            out.append({"sequence": seq, "arm": lab, "encode_id": eid, "group": grp, "n_group_frames": len(ts),
                        "valid_cells": valid, "moving_cells": moving, "stale_cells": int(row.stale_cells),
                        "stale_of_valid": row.stale_of_valid,
                        "stale_mov": row.stale_cells / moving if moving else np.nan})
        print(seq, "done", flush=True)
    df = pd.DataFrame(out)
    df.to_csv(os.path.join(HERE, "sintel_stale_mov.csv"), index=False)
    wide = df.pivot(index="sequence", columns="arm", values="stale_mov")

    L = ["# Sintel STALE_MOV: stale share of moving cells (review follow-up B)\n",
         "**Exploratory reporting, not a new verdict.** STALE_MOV is the confirmatory CCTV test's metric "
         "(pre-registration d62753f), applied after the fact to the saved Sintel sweep. The '> 0.01 in a sequence' "
         "rule is borrowed from that CCTV pre-registration and was not pre-registered for Sintel. "
         "Generated by `p3/review_fixes/b_sintel_stale_mov.py`.\n",
         "- STALE_MOV = stale cells / moving cells. Stale cells (valid, reused at tau = 1 px, |GT| > 2 px) are "
         "`stale_cells` from p3/sweep/results.csv, final pass, tau = 1. Moving cells = valid cells (GT cover >= 0.5) "
         "with |GT| > 2 px, counted from the Sintel GT (lib/gt_grid.py) over the same frames as the row's frame "
         "group (bf 0 arms: `d1` P-frames; B arms: `B_naive`, i.e. the B-frames with the unscaled vector, as in "
         "the CCTV test).",
         f"- Check: valid cells recounted from GT over the same frames equal results.csv `valid_cells` on "
         f"{len(df) - sum(m.startswith('valid') for m in mism)}/{len(df)} rows. "
         f"`valid_cells` and `stale_cells` of every row used are identical in p3/sweep_rerun/results.csv: "
         f"{'yes' if not any(m.startswith('sweep vs') for m in mism) else 'NO'}.",
         f"- {len(seqs)} sequences.\n"]
    if mism:
        L.append("Mismatches:\n" + "\n".join("- " + m for m in mism) + "\n")

    L.append("## Comparisons\n")
    L.append("| comparison | sequences with rise > 0.01 | median STALE_MOV (low) | median STALE_MOV (high) | "
             "median per-sequence difference | sequences with any rise (> 0) |")
    L.append("|---|---|---|---|---|---|")
    summ = {}
    for lab, hi, lo in COMPS:
        d = wide[hi] - wide[lo]
        n = int(d.notna().sum())
        summ[lab] = dict(k=int((d > RULE).sum()), n=n, lo=wide[lo].median(), hi=wide[hi].median(), med=d.median())
        L.append(f"| {lab} | {summ[lab]['k']}/{n} | {wide[lo].median():.4f} | {wide[hi].median():.4f} | "
                 f"{d.median():.4f} | {int((d > 0).sum())}/{n} |")

    def series_table(title, labels):
        L.append(f"\n## {title}: STALE_MOV per sequence\n")
        L.append("| sequence | " + " | ".join(labels) + " |")
        L.append("|---|" + "---|" * len(labels))
        for s in wide.index:
            L.append(f"| {s} | " + " | ".join(f"{wide.at[s, x]:.4f}" for x in labels) + " |")
        L.append("| **median** | " + " | ".join(f"**{wide[x].median():.4f}**" for x in labels) + " |")

    series_table("x264 CRF series (d1)", [f"x264 CRF {c}" for c in CRFS])
    series_table("NVENC QP series (d1)", [f"NVENC QP {q}" for q in NQPS])
    series_table("MPEG-4 series (d1)", [f"MPEG-4 q{q}" for q in MQS])
    series_table("Matched-QP B-frame pairs", ["x264 QP 24 bf 0", "x264 QP 24 bf 2 (B, naive)", "NVENC QP 28 bf 0",
                                              "NVENC QP 28 bf 2 B=P (B, naive)"])
    mv = df[df.arm == "x264 CRF 12"].set_index("sequence")
    L.append("\n## Moving cells per sequence (x264 CRF 12 d1 frames)\n")
    L.append("| sequence | frames | valid cells | moving cells | moving share of valid |")
    L.append("|---|---|---|---|---|")
    for s, r in mv.iterrows():
        L.append(f"| {s} | {r.n_group_frames} | {r.valid_cells} | {r.moving_cells} | "
                 f"{r.moving_cells / r.valid_cells:.4f} |")
    with open(os.path.join(HERE, "sintel_stale_mov.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")
    for k, v in summ.items():
        print(k, v)
    print("mismatches:", len(mism))


if __name__ == "__main__":
    main()
